[workspace]
resolver = "2"
members = ["text-completion", "echo","agent_generator","agent_summarizer"]

[workspace.dependencies]
wit-bindgen = "0.46.0"
inferlet = { path = "../inferlet" }
inferlet-macros = { path = "../inferlet-macros" }
[profile.release]
lto = true
